### ISSUE TITLE
qb-target

### ISSUE THREAD

**Issue by Lordicon** [GouveiaXS/flipcars#2]
Would be nice to have this work with qb-target and a progress bar for players. 10 seconds to flip etc

**Comment by GouveiaXS** [comment]
This does work with qb-target (make sure you are on the newest version V1.2 released approx July 2023):
![image](https://github.com/GouveiaXS/angelicxs-flipcars/assets/99211701/fb32a1ce-42ed-45be-ae26-224a664aeb3f)

Progressbar is a seperate script and I limit the amount of dependencies I put into my scripts. However, if you would like to add it in yourself you would put it in this section:
![image](https://github.com/GouveiaXS/angelicxs-flipcars/assets/99211701/7b240ad8-cce0-490f-9e1e-90f76b6feed4)
Lines 170-180 is where the actual stuff occurs and is where the progress bar portion would be.

**Comment by Lordicon** [comment]
Works great just wish it only showed thirdeye on the car when IsVehicleOnAllWheels = false lol

**Comment by GouveiaXS** [comment]
You can try adding this after `label = "Flip Vehicle"`, but no guarantee it works.
`canInteract = function(entity, distance, data) return IsVehicleOnAllWheels(entity) end,`
